### ISSUE TITLE
recon vertical lines

### ISSUE THREAD

**Issue by zhangy6x** [dmici/NeuTomPy-toolbox#5]
Hi, I tried the FBP recon with CPU following the example code. However, the recon slices are not as expected. They are all vertical lines as attached. Can you please advise?
![screenshot](https://user-images.githubusercontent.com/29611336/121254731-9cf71000-c878-11eb-9279-8323253cfa0f.png)

**Comment by dmici** [comment]
Hi @zhangy6x , can you please attach a screenshot of the plots generated by  the function `ntp.correction_COR`?

**Comment by zhangy6x** [comment]
@dmici Sure! Thanks for the quick response!
![screenshot](https://user-images.githubusercontent.com/29611336/122321475-ec30e680-cef1-11eb-91bb-c6565d7ee735.png)
![screenshot](https://user-images.githubusercontent.com/29611336/122321489-efc46d80-cef1-11eb-82ec-3fcf765cad63.png)

**Comment by dmici** [comment]
The computation of the COR seems OK.

I would like to see your dataset and your script.  Can you upload them somewhere and send the link to neutompy@gmail.com?
